# Start from a Node.js 16 base image
FROM node:20

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json first for caching optimization
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the source code from your local machine into the container
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Command to run the application
CMD ["npm", "start"]
